app-registrations.yaml
Required for testing the https://github.com/hmcts/aks-sds-deploy/pull/277
```
[ ] Yes
[x] No
```
=> Change to Reader on ss-sbox-00-aks

app-registrations.yaml
Fixes https://github.com/hmcts/aks-sds-deploy/pull/277 
```
[ ] Yes
[x] No
```
=> Add more scopes to  DTS SDS AKS version checker

app-registrations.yaml
See https://github.com/hmcts/aks-module-kubernetes/pull/75 and https://github.com/hmcts/aks-sds-deploy/pull/292
=> Remove AKS role assignments from this repo

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-11791
Adding Sanbox cleanup in app registration
```
[ ] Yes
[x] No
```
=> Adding Sanbox cleanup in app registration

app-registrations.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Sanbox Cleardown: Give permissions to SP in sbox envs

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12179
Add test repo to app registrations
```
[ ] Yes
[X] No
```
=> DTSPO-12179 - Add test repo to app registrations

app-registrations.yaml
DTSPO-13971
Adding branch branch identity to allow testing of action without merging to master 
**to be removed once testing is complete
```
[ ] Yes
[ x] No
```
=> adding branch to allow testing of action without merging to master

app-registrations.yaml
[DTSPO-13031](https://tools.hmcts.net/jira/browse/DTSPO-13031)
Added a new fed cred for finops reporting
```
[ ] Yes
[x ] No
```
=> added DTS Reporting App Reg

app-registrations.yaml
=> corrected spelling mistake in name

app-registrations.yaml
Changed sub id
```
[ ] Yes
[ X] No
```
=> changed subscription

app-registrations.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Give 'vm contributor' role to autoshutdown

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13983
* Fix subjects for DTS Orphaned Resource Cleanup
```
[ ] Yes
[x] No
```
=> Fix subjects for DTS Orphaned Resource Cleanup

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13983
* Temporarily add Platform-Prod MG to Orphaned Resource Cleanup for testing
```
[ ] Yes
[x] No
```
=> Temporarily add Platform-Prod MG to Orphaned Resource Cleanup for testing

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13983
* Temporarily remove orphan cleanup to allow clean initialisation of new role creation terraform
```
[ ] Yes
[x] No
```
=> Temporarily remove orphan cleanup to allow clean initialisation of new role creation terraform

app-registrations.yaml
Reverts hmcts/azure-github-federation-config#48
=> Revert "Temporarily remove orphan cleanup to allow clean initialisation of new role creation terraform"

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13983
* Add non-prod management groups to orphan cleanup
```
[ ] Yes
[x] No
```
=> Add non-prod management groups to orphan cleanup

app-registrations.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> assign contributor role to auto-shutdown 

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16389
- Fix typo in the repo name for WAF Monitoring app
=> DTSPO-16389: fix WAF Monitoring repo name

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16389
- Add Reader for the keyvault containing slack webhook url for waf-monitoring slack app
=> DTSPO-16389: reader access of KV containing slack webhook

app-registrations.yaml
DTSPO-17195
Add DTSPO-17195 auto-shutdown test repo
=> DTSPO-17195 - Add DTSPO-17195 auto-shutdown test repo

app-registrations.yaml
[DTSPO-18222](https://tools.hmcts.net/jira/browse/DTSPO-18222)
adding federated access for darts-portal
=> DTSPO-18222 - adding federated access for darts-portal

app-registrations.yaml
DTSPO-18222
adding test app reg
=> DTSPO-18222 - adding test app reg

app-registrations.yaml
DTSPO-18222
DTSPO-18222 - adding new darts-portal app reg
=> DTSPO-18222 - adding new darts-portal app reg

app-registrations.yaml
https://github.com/hmcts/slack-help-bot/issues/382
=> Add GitHub cred for hmcts way indexing

app-registrations.yaml
DTSPO-18362
cleaning up access and adding allowed dev branch access
=> DTSPO-18362 - cleaning up access and adding allowed dev branch access

app-registrations.yaml
Job is failing today for this error message although wasn't last week =/
=> Add environment to hmcts way

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-18467
Pipeline failed to apply for sandbox cleanup, missing subscription that has been removed
Typo in new app reg subjects field
=> Dtspo 18467 workflow update

azure-pipelines.yml
https://tools.hmcts.net/jira/browse/DTSPO-25700
Ubuntu agent version update to latest
=> Ubuntu agent version update to latest

app-registrations.yaml
https://tools.hmcts.net/jira/browse/DTSPO-27573
Add app registration for DTS Auto DB Query
=> DTSPO-27573 Add app registration for DTS Auto DB Query
